/**
 * Author......: Deutsche Telekom Security GmbH
 * License.....: MIT
 * 
 * PuTTY Private Key (PPK) version 2, AES-256-CBC encryption
 * 
 * PPK v2 key derivation:
 *   cipher_key = SHA1(0x00000000 || passphrase) || SHA1(0x00000001 || passphrase) [first 32 bytes]
 *   iv = 0x00 * 16 (all zeros)
 *   mac_key = SHA1("putty-private-key-file-mac-key" || passphrase)
 *   
 * Verification: HMAC-SHA1(mac_key, algorithm || encryption || comment || public_blob || decrypted_private)
 */

#include "common.h"
#include "types.h"
#include "modules.h"
#include "bitops.h"
#include "convert.h"
#include "shared.h"

static const u32   ATTACK_EXEC    = ATTACK_EXEC_INSIDE_KERNEL;
static const u32   DGST_POS0      = 0;
static const u32   DGST_POS1      = 1;
static const u32   DGST_POS2      = 2;
static const u32   DGST_POS3      = 3;
static const u32   DGST_SIZE      = DGST_SIZE_4_5;  // SHA1 = 20 bytes
static const u32   HASH_CATEGORY  = HASH_CATEGORY_PRIVATE_KEY;
static const char *HASH_NAME      = "PuTTY Private Key (PPK), Version 2, AES-256-CBC";
static const u64   KERN_TYPE      = 99200;
static const u32   OPTI_TYPE      = OPTI_TYPE_ZERO_BYTE;
static const u64   OPTS_TYPE      = OPTS_TYPE_STOCK_MODULE
                                  | OPTS_TYPE_PT_GENERATE_LE;
static const u32   SALT_TYPE      = SALT_TYPE_EMBEDDED;
static const char *ST_PASS        = "hashcat";
// Test hash: PPK v2 RSA 2048-bit, generated by puttygen with password "hashcat"
static const char *ST_HASH        = "$ppk$2*7373682d727361*6165733235362d636263*686173686361742d74657374*279*000000077373682d727361000000"
                                    "030100010000010100f29873dc52a9d790e2fce16d93232bfd7f0df8800dffe790b4c41e18f38de19ff817a084c23f330df6"
                                    "5315f78e4a14b90799ee01401e1e41bcc3b4d6c0f5e5dedca05d3749347a0ea88846acc61891bf2a909014b67572a795147b"
                                    "dca3b613ec8071adb6c205e21a629eac8b509fd23e1ac1fa59cb0730ffac0436386ac106132b53da087af3baa3164ea5f56d"
                                    "b401712d49ac6bf971b266403a8f402d7f462e3fed48552bc4e1910d6982cc3304eb738b730c1283185f3875e7bf30969d73"
                                    "bf250da52afbbd6668c4867c2b98583cde4e0aad0c3f32fe0d607d73b1d9f4f3930bc1ae2ef0fe3438441a3c3ec892ed25ba"
                                    "041376867b9eb314ae98901b8f0fc7*672*a289922b282c92716771f3f53b279b0dfb595a04ed09d640e67c15db5ec615407"
                                    "f04f8ae18d74f8c565a8660d292b3e126f1c70d92dcf2ccce5ed013657b81321cf4ffdf087cf7d76be74569ee3e029f31532"
                                    "6b4765dafe9b3bb763b7b156e15e0466937d7d3862df974b8d521de4b93b9f0b3537401a55080c2f5baa54aff3bbfbfad1c5"
                                    "b3a404530d794adeca41563f734037fb93477c35089f60452dff091c72156df55df05f25860b4fcf1b2ca1ce2ee837268a69"
                                    "88e7f379e248e301d85489b220bd6425ae5e82359354babe017b2501f7191c8d48f691c646f148bb4eb07598e9ba97726a8b"
                                    "0dcff472a398da44c17be0493916bcda7174a5db89abb58a8568edafe9abef04430a965fe1800859afb0e829b216e9c92f14"
                                    "bb052ea822d2e6b0b3940814f1160ef38c213b3157eb0e7118a37787b45be70d7efb2a5c1748ee9d05b5d715f9e1980dd1f8"
                                    "4f895dadadeade61e31b451ddd8202764d38c1fca2a03862e760e18ccb1a8aae5be21381cf35fb766f6ddb375ad932ee9fe4"
                                    "ff35aebd347dc3d6418ca26fc477e0eddabee56451870e075df9682319e3bb0cc4ce0de21930ddf7cbcf26ca9a3a1de1f664"
                                    "faff708bcafc5c8ff031b0748d0373010ea6368ab6d0d1d34b65162ff68731a1514630450afe8db5a38a90f445e6892cbdd2"
                                    "792eeabf983f3776644884769e8b284db46bd49cdbf1bc95ea2f6c8b4ddb723a26aa5c80486b6ef477010cb36214940462e4"
                                    "a79d8fe4271f1b94ba9aed9576ba0ea808f34eda231e8f1acc28ad6a33f8e97e66896967be838fc743b19107bd1c7bd54eb6"
                                    "3e11d9695bf535af7e475cf314c38a4fc9f615a00f242ddaf0bee60c966222b24fb7ff8b9ca96d2d2eae4f262b793dab9f0b"
                                    "a31a4d2b2894a75f2e8d28c632a203dcadce665a944ab1ed28b7f94bb70389ee480aec457d9c397*9997e19941a1b91f2c5b"
                                    "065a146dbd78d5254d10";

u32         module_attack_exec    (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ATTACK_EXEC;     }
u32         module_dgst_pos0      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS0;       }
u32         module_dgst_pos1      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS1;       }
u32         module_dgst_pos2      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS2;       }
u32         module_dgst_pos3      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS3;       }
u32         module_dgst_size      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_SIZE;       }
u32         module_hash_category  (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return HASH_CATEGORY;   }
const char *module_hash_name      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return HASH_NAME;       }
u64         module_kern_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return KERN_TYPE;       }
u32         module_opti_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return OPTI_TYPE;       }
u64         module_opts_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return OPTS_TYPE;       }
u32         module_salt_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return SALT_TYPE;       }
const char *module_st_hash        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_HASH;         }
const char *module_st_pass        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_PASS;         }

// Extended salt structure for PPK data
typedef struct ppk
{
  // Algorithm name (e.g., "ssh-rsa", "ssh-dss", "ecdsa-sha2-nistp256", etc.)
  u32 algorithm_buf[16];
  int algorithm_len;

  // Encryption type (always "aes256-cbc" for encrypted PPK v2)
  u32 encryption_buf[8];
  int encryption_len;

  // Key comment
  u32 comment_buf[64];
  int comment_len;

  // Public key blob (binary, decoded from base64)
  u32 public_buf[1024];
  int public_len;

  // Encrypted private key blob (binary, decoded from base64)
  u32 private_buf[2048];
  int private_len;

  // Expected MAC (HMAC-SHA1, 20 bytes)
  u32 mac[5];

} ppk_t;

static const char *SIGNATURE_PPK = "$ppk$";

u64 module_esalt_size (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra)
{
  const u64 esalt_size = (const u64) sizeof (ppk_t);

  return esalt_size;
}

int module_hash_decode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED void *digest_buf, MAYBE_UNUSED salt_t *salt, MAYBE_UNUSED void *esalt_buf, MAYBE_UNUSED void *hook_salt_buf, MAYBE_UNUSED hashinfo_t *hash_info, const char *line_buf, MAYBE_UNUSED const int line_len)
{
  u32 *digest = (u32 *) digest_buf;

  ppk_t *ppk = (ppk_t *) esalt_buf;

  hc_token_t token;

  memset (&token, 0, sizeof (hc_token_t));

  // Hash format: $ppk$2*version*encryption*comment_hex*public_len*public_hex*private_len*private_hex*mac_hex
  // Simplified: $ppk$2*algorithm*encryption*comment*public_len*public_hex*private_len*private_hex*mac

  token.token_cnt = 10;

  token.signatures_cnt    = 1;
  token.signatures_buf[0] = SIGNATURE_PPK;

  // $ppk$
  token.len[0]     = 5;
  token.attr[0]    = TOKEN_ATTR_FIXED_LENGTH
                   | TOKEN_ATTR_VERIFY_SIGNATURE;

  // Version (2)
  token.sep[1]     = '*';
  token.len_min[1] = 1;
  token.len_max[1] = 1;
  token.attr[1]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // Algorithm (hex-encoded, e.g., "7373682d727361" for "ssh-rsa")
  token.sep[2]     = '*';
  token.len_min[2] = 2;
  token.len_max[2] = 128;
  token.attr[2]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // Encryption type (hex-encoded, e.g., "6165733235362d636263" for "aes256-cbc")
  token.sep[3]     = '*';
  token.len_min[3] = 2;
  token.len_max[3] = 64;
  token.attr[3]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // Comment (hex-encoded)
  token.sep[4]     = '*';
  token.len_min[4] = 0;
  token.len_max[4] = 512;
  token.attr[4]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // Public key length
  token.sep[5]     = '*';
  token.len_min[5] = 1;
  token.len_max[5] = 8;
  token.attr[5]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // Public key blob (hex)
  token.sep[6]     = '*';
  token.len_min[6] = 2;
  token.len_max[6] = 8192;
  token.attr[6]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // Private key length
  token.sep[7]     = '*';
  token.len_min[7] = 1;
  token.len_max[7] = 8;
  token.attr[7]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // Private key blob (hex, encrypted)
  token.sep[8]     = '*';
  token.len_min[8] = 32;   // At least 16 bytes encrypted data
  token.len_max[8] = 16384;
  token.attr[8]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // MAC (HMAC-SHA1, 40 hex chars = 20 bytes)
  token.sep[9]     = '*';
  token.len[9]     = 40;
  token.attr[9]    = TOKEN_ATTR_FIXED_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  const int rc_tokenizer = input_tokenizer ((const u8 *) line_buf, line_len, &token);

  if (rc_tokenizer != PARSER_OK) return (rc_tokenizer);

  // Version check (must be 2)
  const u8 *version_pos = token.buf[1];
  const int version = hc_strtoul ((const char *) version_pos, NULL, 10);

  if (version != 2) return (PARSER_SIGNATURE_UNMATCHED);

  // Algorithm (hex-encoded)
  const u8 *algorithm_pos = token.buf[2];
  const int algorithm_len = token.len[2];

  memset (ppk->algorithm_buf, 0, sizeof (ppk->algorithm_buf));
  ppk->algorithm_len = hex_decode (algorithm_pos, algorithm_len, (u8 *) ppk->algorithm_buf);

  if (ppk->algorithm_len > 64) return (PARSER_SALT_LENGTH);

  // Encryption type (hex-encoded)
  const u8 *encryption_pos = token.buf[3];
  const int encryption_len = token.len[3];

  memset (ppk->encryption_buf, 0, sizeof (ppk->encryption_buf));
  ppk->encryption_len = hex_decode (encryption_pos, encryption_len, (u8 *) ppk->encryption_buf);

  // Must be "aes256-cbc" for this module
  if (ppk->encryption_len != 10) return (PARSER_CIPHER);
  if (memcmp (ppk->encryption_buf, "aes256-cbc", 10) != 0) return (PARSER_CIPHER);

  // Comment (hex-encoded)
  const u8 *comment_pos = token.buf[4];
  const int comment_len = token.len[4];

  memset (ppk->comment_buf, 0, sizeof (ppk->comment_buf));
  ppk->comment_len = hex_decode (comment_pos, comment_len, (u8 *) ppk->comment_buf);

  // Public key length (for verification)
  const u8 *public_len_pos = token.buf[5];
  const int public_len_verify = hc_strtoul ((const char *) public_len_pos, NULL, 10);

  // Public key blob (hex)
  const u8 *public_pos = token.buf[6];
  const int public_hex_len = token.len[6];

  memset (ppk->public_buf, 0, sizeof (ppk->public_buf));
  ppk->public_len = hex_decode (public_pos, public_hex_len, (u8 *) ppk->public_buf);

  if (ppk->public_len != public_len_verify) return (PARSER_HASH_LENGTH);

  // Private key length (for verification)
  const u8 *private_len_pos = token.buf[7];
  const int private_len_verify = hc_strtoul ((const char *) private_len_pos, NULL, 10);

  // Private key blob (hex, encrypted)
  const u8 *private_pos = token.buf[8];
  const int private_hex_len = token.len[8];

  memset (ppk->private_buf, 0, sizeof (ppk->private_buf));
  ppk->private_len = hex_decode (private_pos, private_hex_len, (u8 *) ppk->private_buf);

  if (ppk->private_len != private_len_verify) return (PARSER_HASH_LENGTH);

  // Private data must be multiple of AES block size (16 bytes)
  if (ppk->private_len % 16) return (PARSER_HASH_LENGTH);

  // MAC (HMAC-SHA1, 20 bytes)
  const u8 *mac_pos = token.buf[9];

  ppk->mac[0] = hex_to_u32 (mac_pos +  0);
  ppk->mac[1] = hex_to_u32 (mac_pos +  8);
  ppk->mac[2] = hex_to_u32 (mac_pos + 16);
  ppk->mac[3] = hex_to_u32 (mac_pos + 24);
  ppk->mac[4] = hex_to_u32 (mac_pos + 32);

  // Use parts of the data as salt for hashcat deduplication
  salt->salt_buf[0] = ppk->private_buf[0];
  salt->salt_buf[1] = ppk->private_buf[1];
  salt->salt_buf[2] = ppk->private_buf[2];
  salt->salt_buf[3] = ppk->private_buf[3];
  salt->salt_len    = 16;

  // Store expected MAC as digest
  // hex_to_u32 returns LE byte order, but SHA1 h[] stores values in BE format
  // So we need byte_swap to convert LE to BE for comparison
  digest[0] = byte_swap_32 (ppk->mac[0]);
  digest[1] = byte_swap_32 (ppk->mac[1]);
  digest[2] = byte_swap_32 (ppk->mac[2]);
  digest[3] = byte_swap_32 (ppk->mac[3]);
  digest[4] = byte_swap_32 (ppk->mac[4]);

  return (PARSER_OK);
}

int module_hash_encode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const void *digest_buf, MAYBE_UNUSED const salt_t *salt, MAYBE_UNUSED const void *esalt_buf, MAYBE_UNUSED const void *hook_salt_buf, MAYBE_UNUSED const hashinfo_t *hash_info, char *line_buf, MAYBE_UNUSED const int line_size)
{
  const ppk_t *ppk = (const ppk_t *) esalt_buf;

  u8 *out_buf = (u8 *) line_buf;

  int out_len = 0;

  // Start with signature and version
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "%s2*", SIGNATURE_PPK);

  // Algorithm (hex-encoded)
  out_len += hex_encode ((const u8 *) ppk->algorithm_buf, ppk->algorithm_len, out_buf + out_len);
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "*");

  // Encryption (hex-encoded)
  out_len += hex_encode ((const u8 *) ppk->encryption_buf, ppk->encryption_len, out_buf + out_len);
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "*");

  // Comment (hex-encoded)
  out_len += hex_encode ((const u8 *) ppk->comment_buf, ppk->comment_len, out_buf + out_len);
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "*");

  // Public length and data
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "%d*", ppk->public_len);
  out_len += hex_encode ((const u8 *) ppk->public_buf, ppk->public_len, out_buf + out_len);
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "*");

  // Private length and data
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "%d*", ppk->private_len);
  out_len += hex_encode ((const u8 *) ppk->private_buf, ppk->private_len, out_buf + out_len);
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "*");

  // MAC
  out_len += snprintf ((char *) out_buf + out_len, line_size - out_len, "%08x%08x%08x%08x%08x",
    byte_swap_32 (ppk->mac[0]),
    byte_swap_32 (ppk->mac[1]),
    byte_swap_32 (ppk->mac[2]),
    byte_swap_32 (ppk->mac[3]),
    byte_swap_32 (ppk->mac[4]));

  return out_len;
}

void module_init (module_ctx_t *module_ctx)
{
  module_ctx->module_context_size             = MODULE_CONTEXT_SIZE_CURRENT;
  module_ctx->module_interface_version        = MODULE_INTERFACE_VERSION_CURRENT;

  module_ctx->module_attack_exec              = module_attack_exec;
  module_ctx->module_benchmark_esalt          = MODULE_DEFAULT;
  module_ctx->module_benchmark_hook_salt      = MODULE_DEFAULT;
  module_ctx->module_benchmark_mask           = MODULE_DEFAULT;
  module_ctx->module_benchmark_charset        = MODULE_DEFAULT;
  module_ctx->module_benchmark_salt           = MODULE_DEFAULT;
  module_ctx->module_bridge_name              = MODULE_DEFAULT;
  module_ctx->module_bridge_type              = MODULE_DEFAULT;
  module_ctx->module_build_plain_postprocess  = MODULE_DEFAULT;
  module_ctx->module_deep_comp_kernel         = MODULE_DEFAULT;
  module_ctx->module_deprecated_notice        = MODULE_DEFAULT;
  module_ctx->module_dgst_pos0                = module_dgst_pos0;
  module_ctx->module_dgst_pos1                = module_dgst_pos1;
  module_ctx->module_dgst_pos2                = module_dgst_pos2;
  module_ctx->module_dgst_pos3                = module_dgst_pos3;
  module_ctx->module_dgst_size                = module_dgst_size;
  module_ctx->module_dictstat_disable         = MODULE_DEFAULT;
  module_ctx->module_esalt_size               = module_esalt_size;
  module_ctx->module_extra_buffer_size        = MODULE_DEFAULT;
  module_ctx->module_extra_tmp_size           = MODULE_DEFAULT;
  module_ctx->module_extra_tuningdb_block     = MODULE_DEFAULT;
  module_ctx->module_forced_outfile_format    = MODULE_DEFAULT;
  module_ctx->module_hash_binary_count        = MODULE_DEFAULT;
  module_ctx->module_hash_binary_parse        = MODULE_DEFAULT;
  module_ctx->module_hash_binary_save         = MODULE_DEFAULT;
  module_ctx->module_hash_decode_postprocess  = MODULE_DEFAULT;
  module_ctx->module_hash_decode_potfile      = MODULE_DEFAULT;
  module_ctx->module_hash_decode_zero_hash    = MODULE_DEFAULT;
  module_ctx->module_hash_decode              = module_hash_decode;
  module_ctx->module_hash_encode_status       = MODULE_DEFAULT;
  module_ctx->module_hash_encode_potfile      = MODULE_DEFAULT;
  module_ctx->module_hash_encode              = module_hash_encode;
  module_ctx->module_hash_init_selftest       = MODULE_DEFAULT;
  module_ctx->module_hash_mode                = MODULE_DEFAULT;
  module_ctx->module_hash_category            = module_hash_category;
  module_ctx->module_hash_name                = module_hash_name;
  module_ctx->module_hashes_count_min         = MODULE_DEFAULT;
  module_ctx->module_hashes_count_max         = MODULE_DEFAULT;
  module_ctx->module_hlfmt_disable            = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_size    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_init    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_term    = MODULE_DEFAULT;
  module_ctx->module_hook12                   = MODULE_DEFAULT;
  module_ctx->module_hook23                   = MODULE_DEFAULT;
  module_ctx->module_hook_salt_size           = MODULE_DEFAULT;
  module_ctx->module_hook_size                = MODULE_DEFAULT;
  module_ctx->module_jit_build_options        = MODULE_DEFAULT;
  module_ctx->module_jit_cache_disable        = MODULE_DEFAULT;
  module_ctx->module_kernel_accel_max         = MODULE_DEFAULT;
  module_ctx->module_kernel_accel_min         = MODULE_DEFAULT;
  module_ctx->module_kernel_loops_max         = MODULE_DEFAULT;
  module_ctx->module_kernel_loops_min         = MODULE_DEFAULT;
  module_ctx->module_kernel_threads_max       = MODULE_DEFAULT;
  module_ctx->module_kernel_threads_min       = MODULE_DEFAULT;
  module_ctx->module_kern_type                = module_kern_type;
  module_ctx->module_kern_type_dynamic        = MODULE_DEFAULT;
  module_ctx->module_opti_type                = module_opti_type;
  module_ctx->module_opts_type                = module_opts_type;
  module_ctx->module_outfile_check_disable    = MODULE_DEFAULT;
  module_ctx->module_outfile_check_nocomp     = MODULE_DEFAULT;
  module_ctx->module_potfile_custom_check     = MODULE_DEFAULT;
  module_ctx->module_potfile_disable          = MODULE_DEFAULT;
  module_ctx->module_potfile_keep_all_hashes  = MODULE_DEFAULT;
  module_ctx->module_pwdump_column            = MODULE_DEFAULT;
  module_ctx->module_pw_max                   = MODULE_DEFAULT;
  module_ctx->module_pw_min                   = MODULE_DEFAULT;
  module_ctx->module_salt_max                 = MODULE_DEFAULT;
  module_ctx->module_salt_min                 = MODULE_DEFAULT;
  module_ctx->module_salt_type                = module_salt_type;
  module_ctx->module_separator                = MODULE_DEFAULT;
  module_ctx->module_st_hash                  = module_st_hash;
  module_ctx->module_st_pass                  = module_st_pass;
  module_ctx->module_tmp_size                 = MODULE_DEFAULT;
  module_ctx->module_unstable_warning         = MODULE_DEFAULT;
  module_ctx->module_warmup_disable           = MODULE_DEFAULT;
}
