/**
 * Author......: Deutsche Telekom Security GmbH
 * License.....: MIT
 *
 * PuTTY Private Key (PPK) version 3, AES-256-CBC with Argon2id
 */

#include "common.h"
#include "types.h"
#include "modules.h"
#include "bitops.h"
#include "convert.h"
#include "shared.h"
#include "memory.h"
#include "argon2_common.h"

#define ARGON2_VERSION_13   0x13
#define ARGON2_TYPE_ID      2

static const u32   ATTACK_EXEC    = ATTACK_EXEC_OUTSIDE_KERNEL;
static const u32   DGST_POS0      = 0;
static const u32   DGST_POS1      = 1;
static const u32   DGST_POS2      = 2;
static const u32   DGST_POS3      = 3;
static const u32   DGST_SIZE      = DGST_SIZE_4_8;  // SHA-256 output (32 bytes)
static const u32   HASH_CATEGORY  = HASH_CATEGORY_PRIVATE_KEY;
static const char *HASH_NAME      = "PuTTY Private Key (PPK) v3, Argon2id + AES-256-CBC";
static const u64   KERN_TYPE      = 99210;
static const u32   OPTI_TYPE      = OPTI_TYPE_ZERO_BYTE
                                  | OPTI_TYPE_SLOW_HASH_DIMY_LOOP;
static const u64   OPTS_TYPE      = OPTS_TYPE_STOCK_MODULE
                                  | OPTS_TYPE_PT_GENERATE_LE
                                  | OPTS_TYPE_NATIVE_THREADS
                                  | OPTS_TYPE_THREAD_MULTI_DISABLE
                                  | OPTS_TYPE_MP_MULTI_DISABLE;
static const u32   SALT_TYPE      = SALT_TYPE_EMBEDDED;
static const char *ST_PASS        = "hashcat";
// Test hash: PPK v3 RSA 2048-bit, generated by puttygen with password "hashcat"
static const char *ST_HASH        = "$ppk$3*7373682d727361*6165733235362d636263*686173686361742d74657374*8192*5*1*23b9cc046d6d9af8e60be2e"
                                    "6eed39d2a*279*000000077373682d72736100000003010001000001010098bb6c83ccc27f6fcfed487e58b2d93187bb3401"
                                    "a0931f45f4d02930b1a5c5d4e305a487f6a19f4ea125ef08a5f5452defd64c18e0da11eea41f905368cafbe61dea46a8a315"
                                    "f55018129cdb830dad3a43ee8d45300c1aabd9de9878bd7805930b331c649ff8ae723aef6aa7bffa09b9efa08e57ae9406d3"
                                    "35063a7d0a13bc18731a21c8797d09a063d66b914dab2e6878e9c4a194526775c19554373b92d218904ea79d7a149ebbbf62"
                                    "03baeec704aa227a5630cdb840a14fda4ff4382e26689a2df3520e19de4f905f8d2a13d53f50d7907ad3b1b07a20dafbf8e1"
                                    "c786cf831eb775519ca03d1334b50c37983361508878cd1be2d0e11ce80476e25eccfa51*672*9756c8801c2642539ea538f"
                                    "3c22c25e8a91dd61aa7e898d6ebcf35f4f4d11c8d03dd5e4b77e6d8accc61dc9ef8ac5fc2bf53c2b9dc45159031de698865f"
                                    "90e7edb11fb912f6f32f0e42bfe597782d8c69355e15eb112fbfa82adee68094180f85e90f757db7bc12a047e95372bf297d"
                                    "857729a7ed29381c0d9f99610f60a0268ff35f6986ab760155b2d4247fc00af69c8e009f52453a9788b6e7c4063820a8a0ba"
                                    "9f28d8df832cbfab6d29848d5b7665534438232790da8a47df5601958e6b2cb1582d9e515a5b70c10a442c9902d49f3fb319"
                                    "553a875d677d3ecab3813731a6056a14af6b3b0996ade62a046ed06beb18a571745850bbf1b007fd39e4d079cd13652d9756"
                                    "b1d7c2c2fe3c1400d3555764f4c7ce2e825cfa012a3ada6baaa7fd58022060aa36da310acdd87b095a402e3325751d4d6877"
                                    "9d1bb9e336d57e2083565c05444bcae0a0c2b8d7bf19a5c52709f5cca52bca1d0750a1e2b740a865d8380fec80e32b9e5d19"
                                    "81da676f36435461a11b7f423f24f94d867a5c5d327a8486d9a6bae62172b3fd303fc231e981e83d29416579fa592600fc41"
                                    "5d727c764cf4eddf5ff492c2000556c240787e108ca94b0bd2fdc53e1a1f6e49bf871162be3e3de7aef8819f0db008cd304f"
                                    "90bc3019b8f782dd77456b8865959dda6dcc00d8a0a3c57b827844266cf208919641c690ebe5f9780e642f41b80b5017e32e"
                                    "a7006d7695b1c29a3f8b68c34c0695b47ca94b0ef601cc4e3ced893880cb61b6d68cabcb7386f5a155f22b53a3852b277a79"
                                    "4016d7085d8eaf2a4a69a37b2bc95e03446feeb0c405ff660c17ef9fd9be52f8cc6d8e5fb0c384e91b9ac36b50831d1afc17"
                                    "733b7faafa45b5d9d70583848c28586e9b1ebd0a03559c9fb149f05303aaa4e80427a4492d920800f38652e9b029ad08ae36"
                                    "4786a84195fc61abb51df*2d4ae0f2609f6900dbefb4a2d8760da6dc37d37de63e97fdd4f1677050de7ad9";

u32         module_attack_exec    (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ATTACK_EXEC;     }
u32         module_dgst_pos0      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS0;       }
u32         module_dgst_pos1      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS1;       }
u32         module_dgst_pos2      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS2;       }
u32         module_dgst_pos3      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS3;       }
u32         module_dgst_size      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_SIZE;       }
u32         module_hash_category  (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return HASH_CATEGORY;   }
const char *module_hash_name      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return HASH_NAME;       }
u64         module_kern_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return KERN_TYPE;       }
u32         module_opti_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return OPTI_TYPE;       }
u64         module_opts_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return OPTS_TYPE;       }
u32         module_salt_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return SALT_TYPE;       }
const char *module_st_hash        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_HASH;         }
const char *module_st_pass        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_PASS;         }

static const char *SIGNATURE_PPK3 = "$ppk$3";

#define PPK_ALGORITHM_MAX    64
#define PPK_ENCRYPTION_MAX   32
#define PPK_COMMENT_MAX      256
#define PPK_PUBLIC_MAX       4096
#define PPK_PRIVATE_MAX      8192

typedef struct ppk3
{
  u32 algorithm_buf[PPK_ALGORITHM_MAX / 4];
  int algorithm_len;

  u32 encryption_buf[PPK_ENCRYPTION_MAX / 4];
  int encryption_len;

  u32 comment_buf[PPK_COMMENT_MAX / 4];
  int comment_len;

  u32 public_buf[PPK_PUBLIC_MAX / 4];
  int public_len;

  u32 private_buf[PPK_PRIVATE_MAX / 4];
  int private_len;

  u32 mac[8];  // SHA-256 = 32 bytes

} ppk3_t;

typedef struct merged_options
{
  argon2_options_t argon2_options;

  ppk3_t ppk3;

} merged_options_t;

#include "argon2_common.c"

typedef struct ppk3_tmp
{
  // Argon2 output (80 bytes for PPK v3)
  // bytes 0-31: AES key
  // bytes 32-47: IV
  // bytes 48-79: MAC key

  u32 key[8];      // 32 bytes AES-256 key
  u32 iv[4];       // 16 bytes IV
  u32 mac_key[8];  // 32 bytes MAC key

} ppk3_tmp_t;

u64 module_esalt_size (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra)
{
  const u64 esalt_size = (const u64) sizeof (merged_options_t);

  return esalt_size;
}

u64 module_tmp_size (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra)
{
  const u64 tmp_size = sizeof (ppk3_tmp_t);

  return tmp_size;
}

int module_hash_decode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED void *digest_buf, MAYBE_UNUSED salt_t *salt, MAYBE_UNUSED void *esalt_buf, MAYBE_UNUSED void *hook_salt_buf, MAYBE_UNUSED hashinfo_t *hash_info, const char *line_buf, MAYBE_UNUSED const int line_len)
{
  u32 *digest = (u32 *) digest_buf;

  merged_options_t *merged_options = (merged_options_t *) esalt_buf;

  argon2_options_t *argon2_options = &merged_options->argon2_options;

  ppk3_t *ppk3 = &merged_options->ppk3;

  // Zero out the structures to avoid garbage data beyond actual content
  memset (merged_options, 0, sizeof (merged_options_t));

  hc_token_t token;

  memset (&token, 0, sizeof (hc_token_t));

  // Format: $ppk$3*algorithm*encryption*comment*argon2_memory*argon2_passes*argon2_parallelism*argon2_salt*pub_len*pub*priv_len*priv*mac

  token.token_cnt  = 13;

  token.signatures_cnt    = 1;
  token.signatures_buf[0] = SIGNATURE_PPK3;

  // signature $ppk$3
  token.sep[0]     = '*';
  token.len[0]     = 6;
  token.attr[0]    = TOKEN_ATTR_FIXED_LENGTH
                   | TOKEN_ATTR_VERIFY_SIGNATURE;

  // algorithm (hex encoded)
  token.sep[1]     = '*';
  token.len_min[1] = 2;
  token.len_max[1] = PPK_ALGORITHM_MAX * 2;
  token.attr[1]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // encryption (hex encoded)
  token.sep[2]     = '*';
  token.len_min[2] = 2;
  token.len_max[2] = PPK_ENCRYPTION_MAX * 2;
  token.attr[2]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // comment (hex encoded)
  token.sep[3]     = '*';
  token.len_min[3] = 0;
  token.len_max[3] = PPK_COMMENT_MAX * 2;
  token.attr[3]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // argon2 memory (KB)
  token.sep[4]     = '*';
  token.len_min[4] = 1;
  token.len_max[4] = 10;
  token.attr[4]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // argon2 passes (iterations)
  token.sep[5]     = '*';
  token.len_min[5] = 1;
  token.len_max[5] = 10;
  token.attr[5]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // argon2 parallelism
  token.sep[6]     = '*';
  token.len_min[6] = 1;
  token.len_max[6] = 3;
  token.attr[6]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // argon2 salt (hex)
  token.sep[7]     = '*';
  token.len[7]     = 32;  // 16 bytes = 32 hex chars
  token.attr[7]    = TOKEN_ATTR_FIXED_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // public key length
  token.sep[8]     = '*';
  token.len_min[8] = 1;
  token.len_max[8] = 5;
  token.attr[8]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // public key (hex)
  token.sep[9]     = '*';
  token.len_min[9] = 2;
  token.len_max[9] = PPK_PUBLIC_MAX * 2;
  token.attr[9]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // private key length
  token.sep[10]    = '*';
  token.len_min[10] = 1;
  token.len_max[10] = 5;
  token.attr[10]   = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_DIGIT;

  // private key (hex, encrypted)
  token.sep[11]    = '*';
  token.len_min[11] = 32;  // minimum 16 bytes
  token.len_max[11] = PPK_PRIVATE_MAX * 2;
  token.attr[11]   = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  // mac (hex) - SHA-256 = 64 hex chars
  token.sep[12]    = '*';
  token.len[12]    = 64;
  token.attr[12]   = TOKEN_ATTR_FIXED_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

  const int rc_tokenizer = input_tokenizer ((const u8 *) line_buf, line_len, &token);

  if (rc_tokenizer != PARSER_OK) return (rc_tokenizer);

  // algorithm
  const u8 *algorithm_pos = token.buf[1];
  const int algorithm_len = token.len[1];

  ppk3->algorithm_len = hex_decode (algorithm_pos, algorithm_len, (u8 *) ppk3->algorithm_buf);

  // encryption
  const u8 *encryption_pos = token.buf[2];
  const int encryption_len = token.len[2];

  ppk3->encryption_len = hex_decode (encryption_pos, encryption_len, (u8 *) ppk3->encryption_buf);

  // verify encryption is aes256-cbc
  if (ppk3->encryption_len != 10) return (PARSER_HASH_ENCODING);
  if (memcmp (ppk3->encryption_buf, "aes256-cbc", 10) != 0) return (PARSER_HASH_ENCODING);

  // comment
  const u8 *comment_pos = token.buf[3];
  const int comment_len = token.len[3];

  ppk3->comment_len = hex_decode (comment_pos, comment_len, (u8 *) ppk3->comment_buf);

  // argon2 memory
  const u8 *mem_pos = token.buf[4];
  const u32 mem = hc_strtoul ((const char *) mem_pos, NULL, 10);

  if (mem < 1) return (PARSER_HASH_VALUE);

  // argon2 passes
  const u8 *iter_pos = token.buf[5];
  const u32 iter = hc_strtoul ((const char *) iter_pos, NULL, 10);

  if (iter < 1) return (PARSER_SALT_ITERATION);

  salt->salt_iter = iter * ARGON2_SYNC_POINTS;

  // argon2 parallelism
  const u8 *par_pos = token.buf[6];
  const u32 par = hc_strtoul ((const char *) par_pos, NULL, 10);

  if (par < 1 || par > 32) return (PARSER_HASH_VALUE);

  salt->salt_dimy = par;

  // argon2 salt
  const u8 *salt_pos = token.buf[7];

  salt->salt_len = hex_decode (salt_pos, 32, (u8 *) salt->salt_buf);

  // argon2 options
  argon2_options->type                = ARGON2_TYPE_ID;  // Argon2id
  argon2_options->version             = ARGON2_VERSION_13;
  argon2_options->iterations          = iter;
  argon2_options->parallelism         = par;
  argon2_options->memory_usage_in_kib = mem;
  argon2_options->segment_length      = MAX (2, (mem / (ARGON2_SYNC_POINTS * par)));
  argon2_options->lane_length         = argon2_options->segment_length * ARGON2_SYNC_POINTS;
  argon2_options->memory_block_count  = argon2_options->lane_length * par;
  argon2_options->digest_len          = 80;  // PPK v3 needs 80 bytes from Argon2

  // public key length
  const u8 *pub_len_pos = token.buf[8];
  const int pub_len = hc_strtoul ((const char *) pub_len_pos, NULL, 10);

  // public key
  const u8 *pub_pos = token.buf[9];
  const int pub_hex_len = token.len[9];

  if (pub_hex_len / 2 != pub_len) return (PARSER_HASH_LENGTH);

  ppk3->public_len = hex_decode (pub_pos, pub_hex_len, (u8 *) ppk3->public_buf);

  // private key length
  const u8 *priv_len_pos = token.buf[10];
  const int priv_len = hc_strtoul ((const char *) priv_len_pos, NULL, 10);

  // private key (encrypted)
  const u8 *priv_pos = token.buf[11];
  const int priv_hex_len = token.len[11];

  if (priv_hex_len / 2 != priv_len) return (PARSER_HASH_LENGTH);
  if (priv_len % 16 != 0) return (PARSER_HASH_LENGTH);  // must be multiple of AES block size

  ppk3->private_len = hex_decode (priv_pos, priv_hex_len, (u8 *) ppk3->private_buf);

  // mac (SHA-256)
  const u8 *mac_pos = token.buf[12];

  ppk3->mac[0] = hex_to_u32 (mac_pos +  0);
  ppk3->mac[1] = hex_to_u32 (mac_pos +  8);
  ppk3->mac[2] = hex_to_u32 (mac_pos + 16);
  ppk3->mac[3] = hex_to_u32 (mac_pos + 24);
  ppk3->mac[4] = hex_to_u32 (mac_pos + 32);
  ppk3->mac[5] = hex_to_u32 (mac_pos + 40);
  ppk3->mac[6] = hex_to_u32 (mac_pos + 48);
  ppk3->mac[7] = hex_to_u32 (mac_pos + 56);

  // Set digest (MAC value for comparison)
  // hex_to_u32("2998a556") returns 0x56a59829 (LE byte order)
  // SHA-256 h[] stores values in BE format (bytes 29 98 a5 56 -> h[0] = 0x2998a556)
  // So we need byte_swap to convert LE to BE for comparison
  digest[0] = byte_swap_32 (ppk3->mac[0]);
  digest[1] = byte_swap_32 (ppk3->mac[1]);
  digest[2] = byte_swap_32 (ppk3->mac[2]);
  digest[3] = byte_swap_32 (ppk3->mac[3]);
  digest[4] = byte_swap_32 (ppk3->mac[4]);
  digest[5] = byte_swap_32 (ppk3->mac[5]);
  digest[6] = byte_swap_32 (ppk3->mac[6]);
  digest[7] = byte_swap_32 (ppk3->mac[7]);

  return (PARSER_OK);
}

int module_hash_encode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const void *digest_buf, MAYBE_UNUSED const salt_t *salt, MAYBE_UNUSED const void *esalt_buf, MAYBE_UNUSED const void *hook_salt_buf, MAYBE_UNUSED const hashinfo_t *hash_info, char *line_buf, MAYBE_UNUSED const int line_size)
{
  const merged_options_t *merged_options = (const merged_options_t *) esalt_buf;

  const argon2_options_t *argon2_options = &merged_options->argon2_options;

  const ppk3_t *ppk3 = &merged_options->ppk3;

  // Hex encode all components

  char *algorithm_hex = (char *) hcmalloc (ppk3->algorithm_len * 2 + 1);
  hex_encode ((const u8 *) ppk3->algorithm_buf, ppk3->algorithm_len, (u8 *) algorithm_hex);

  char *encryption_hex = (char *) hcmalloc (ppk3->encryption_len * 2 + 1);
  hex_encode ((const u8 *) ppk3->encryption_buf, ppk3->encryption_len, (u8 *) encryption_hex);

  char *comment_hex = (char *) hcmalloc (ppk3->comment_len * 2 + 1);
  hex_encode ((const u8 *) ppk3->comment_buf, ppk3->comment_len, (u8 *) comment_hex);

  char *salt_hex = (char *) hcmalloc (salt->salt_len * 2 + 1);
  hex_encode ((const u8 *) salt->salt_buf, salt->salt_len, (u8 *) salt_hex);

  char *public_hex = (char *) hcmalloc (ppk3->public_len * 2 + 1);
  hex_encode ((const u8 *) ppk3->public_buf, ppk3->public_len, (u8 *) public_hex);

  char *private_hex = (char *) hcmalloc (ppk3->private_len * 2 + 1);
  hex_encode ((const u8 *) ppk3->private_buf, ppk3->private_len, (u8 *) private_hex);

  char mac_hex[65];
  snprintf (mac_hex, sizeof (mac_hex), "%08x%08x%08x%08x%08x%08x%08x%08x",
    ppk3->mac[0], ppk3->mac[1], ppk3->mac[2], ppk3->mac[3],
    ppk3->mac[4], ppk3->mac[5], ppk3->mac[6], ppk3->mac[7]);

  int line_len = snprintf (line_buf, line_size,
    "%s*%s*%s*%s*%u*%u*%u*%s*%d*%s*%d*%s*%s",
    SIGNATURE_PPK3,
    algorithm_hex,
    encryption_hex,
    comment_hex,
    argon2_options->memory_usage_in_kib,
    argon2_options->iterations,
    argon2_options->parallelism,
    salt_hex,
    ppk3->public_len,
    public_hex,
    ppk3->private_len,
    private_hex,
    mac_hex);

  hcfree (algorithm_hex);
  hcfree (encryption_hex);
  hcfree (comment_hex);
  hcfree (salt_hex);
  hcfree (public_hex);
  hcfree (private_hex);

  return line_len;
}

void module_init (module_ctx_t *module_ctx)
{
  module_ctx->module_context_size             = MODULE_CONTEXT_SIZE_CURRENT;
  module_ctx->module_interface_version        = MODULE_INTERFACE_VERSION_CURRENT;

  module_ctx->module_attack_exec              = module_attack_exec;
  module_ctx->module_benchmark_esalt          = MODULE_DEFAULT;
  module_ctx->module_benchmark_hook_salt      = MODULE_DEFAULT;
  module_ctx->module_benchmark_mask           = MODULE_DEFAULT;
  module_ctx->module_benchmark_charset        = MODULE_DEFAULT;
  module_ctx->module_benchmark_salt           = MODULE_DEFAULT;
  module_ctx->module_bridge_name              = MODULE_DEFAULT;
  module_ctx->module_bridge_type              = MODULE_DEFAULT;
  module_ctx->module_build_plain_postprocess  = MODULE_DEFAULT;
  module_ctx->module_deep_comp_kernel         = MODULE_DEFAULT;
  module_ctx->module_deprecated_notice        = MODULE_DEFAULT;
  module_ctx->module_usage_notice             = MODULE_DEFAULT;
  module_ctx->module_dgst_pos0                = module_dgst_pos0;
  module_ctx->module_dgst_pos1                = module_dgst_pos1;
  module_ctx->module_dgst_pos2                = module_dgst_pos2;
  module_ctx->module_dgst_pos3                = module_dgst_pos3;
  module_ctx->module_dgst_size                = module_dgst_size;
  module_ctx->module_dictstat_disable         = MODULE_DEFAULT;
  module_ctx->module_esalt_size               = module_esalt_size;
  module_ctx->module_extra_buffer_size        = argon2_module_extra_buffer_size;
  module_ctx->module_extra_tmp_size           = MODULE_DEFAULT;
  module_ctx->module_extra_tuningdb_block     = argon2_module_extra_tuningdb_block;
  module_ctx->module_forced_outfile_format    = MODULE_DEFAULT;
  module_ctx->module_hash_binary_count        = MODULE_DEFAULT;
  module_ctx->module_hash_binary_parse        = MODULE_DEFAULT;
  module_ctx->module_hash_binary_save         = MODULE_DEFAULT;
  module_ctx->module_hash_decode_postprocess  = MODULE_DEFAULT;
  module_ctx->module_hash_decode_potfile      = MODULE_DEFAULT;
  module_ctx->module_hash_decode_zero_hash    = MODULE_DEFAULT;
  module_ctx->module_hash_decode              = module_hash_decode;
  module_ctx->module_hash_encode_status       = MODULE_DEFAULT;
  module_ctx->module_hash_encode_potfile      = MODULE_DEFAULT;
  module_ctx->module_hash_encode              = module_hash_encode;
  module_ctx->module_hash_init_selftest       = MODULE_DEFAULT;
  module_ctx->module_hash_mode                = MODULE_DEFAULT;
  module_ctx->module_hash_category            = module_hash_category;
  module_ctx->module_hash_name                = module_hash_name;
  module_ctx->module_hashes_count_min         = MODULE_DEFAULT;
  module_ctx->module_hashes_count_max         = MODULE_DEFAULT;
  module_ctx->module_hlfmt_disable            = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_size    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_init    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_term    = MODULE_DEFAULT;
  module_ctx->module_hook12                   = MODULE_DEFAULT;
  module_ctx->module_hook23                   = MODULE_DEFAULT;
  module_ctx->module_hook_salt_size           = MODULE_DEFAULT;
  module_ctx->module_hook_size                = MODULE_DEFAULT;
  module_ctx->module_jit_build_options        = argon2_module_jit_build_options;
  module_ctx->module_jit_cache_disable        = MODULE_DEFAULT;
  module_ctx->module_kernel_accel_max         = MODULE_DEFAULT;
  module_ctx->module_kernel_accel_min         = MODULE_DEFAULT;
  module_ctx->module_kernel_loops_max         = MODULE_DEFAULT;
  module_ctx->module_kernel_loops_min         = MODULE_DEFAULT;
  module_ctx->module_kernel_threads_max       = MODULE_DEFAULT;
  module_ctx->module_kernel_threads_min       = MODULE_DEFAULT;
  module_ctx->module_kern_type                = module_kern_type;
  module_ctx->module_kern_type_dynamic        = MODULE_DEFAULT;
  module_ctx->module_opti_type                = module_opti_type;
  module_ctx->module_opts_type                = module_opts_type;
  module_ctx->module_outfile_check_disable    = MODULE_DEFAULT;
  module_ctx->module_outfile_check_nocomp     = MODULE_DEFAULT;
  module_ctx->module_potfile_custom_check     = MODULE_DEFAULT;
  module_ctx->module_potfile_disable          = MODULE_DEFAULT;
  module_ctx->module_potfile_keep_all_hashes  = MODULE_DEFAULT;
  module_ctx->module_pwdump_column            = MODULE_DEFAULT;
  module_ctx->module_pw_max                   = MODULE_DEFAULT;
  module_ctx->module_pw_min                   = MODULE_DEFAULT;
  module_ctx->module_salt_max                 = MODULE_DEFAULT;
  module_ctx->module_salt_min                 = MODULE_DEFAULT;
  module_ctx->module_salt_type                = module_salt_type;
  module_ctx->module_separator                = MODULE_DEFAULT;
  module_ctx->module_st_hash                  = module_st_hash;
  module_ctx->module_st_pass                  = module_st_pass;
  module_ctx->module_tmp_size                 = module_tmp_size;
  module_ctx->module_unstable_warning         = MODULE_DEFAULT;
  module_ctx->module_warmup_disable           = MODULE_DEFAULT;
}
