#!/usr/bin/env perl

##
## Author......: See docs/credits.txt
## License.....: MIT
##

use strict;
use warnings;

use Crypt::Mode::ECB;
use Digest::SHA qw (sha1);

sub module_constraints { [[0, 256], [-1, -1], [-1, -1], [-1, -1], [-1, -1]] }

# KWallet byte swaps every 32 bit word of the file before it hands it to Blowfish,
# which is a KDE bug the on disk format is stuck with.

sub kwallet_alter_endianity
{
  my $in = shift;

  my $out = "";

  for (my $i = 0; $i < length ($in); $i += 4)
  {
    $out .= scalar reverse substr ($in, $i, 4);
  }

  return $out;
}

# password2hash() from KWallet: the password is cut into 16 byte chunks, every chunk is
# hashed 2000 times, and the chunk digests are glued into a 20, 40 or 56 byte key. The
# fourth chunk takes everything that is left instead of just 16 byte.

sub kwallet_password2hash
{
  my $password = shift;

  my $plength = length ($password);

  my $out = "";

  my $oindex = 0;
  my $i      = 0;

  while (1)
  {
    last if (($i != 0) && ($i >= $plength));

    my $left = $plength - $i;

    my $n = (($oindex >= 60) || ($left < 16)) ? $left : 16;

    my $buf = sha1 (substr ($password, $i, $n));

    for (my $j = 1; $j < 2000; $j++)
    {
      $buf = sha1 ($buf);
    }

    $out .= $buf;

    last if ($oindex >= 60);

    $oindex += 20;
    $i      += 16;
  }

  return substr ($out,  0, 20) if ($plength <= 16);
  return substr ($out,  0, 40) if ($plength <= 32);
  return substr ($out,  0, 56) if ($plength <= 48);

  return substr ($out,  0, 14)
       . substr ($out, 20, 14)
       . substr ($out, 40, 14)
       . substr ($out, 60, 14);
}

# the 64 byte header before encryption: 8 byte random block, the payload size and 52 byte
# of payload. The size field is stored reversed here because the reader swaps it back after
# decrypting, and the payload needs at least 12 zero bytes for the reader to accept the key
# - a real wallet has around 30.

sub kwallet_random_plain
{
  my $ct_len = shift;

  my $payload = random_bytes (52);

  for (my $i = 0; $i < 52; $i += 3)
  {
    substr ($payload, $i, 1) = "\x00";
  }

  return unpack ("H*", random_bytes (8) . scalar reverse (pack ("N", $ct_len - 12)) . $payload);
}

sub module_generate_hash
{
  my $word   = shift;
  my $salt   = shift; # an old wallet has no salt
  my $plain  = shift;
  my $ct_len = shift // 88;

  $plain = kwallet_random_plain ($ct_len) unless defined $plain;

  $plain = pack ("H*", $plain);

  my $key = kwallet_password2hash ($word);

  my $ecb = Crypt::Mode::ECB->new ('Blowfish', 0);

  my $ct_sw = substr ($plain, 0, 8) . $ecb->encrypt (substr ($plain, 8, 56), $key);

  my $ct = kwallet_alter_endianity ($ct_sw);

  my $hash = sprintf ('$kwallet$%d$%s', $ct_len, unpack ("H*", $ct));

  return $hash;
}

sub module_verify_hash
{
  my $line = shift;

  my ($hash, $word) = split (':', $line);

  return unless defined $hash;
  return unless defined $word;

  my @data = split ('\$', $hash);

  return unless scalar @data == 4;

  shift @data; # leading empty field

  my $signature = shift @data;
  my $ct_len    = shift @data;
  my $ct        = shift @data;

  return unless $signature eq 'kwallet';
  return unless length ($ct) == 128;

  my $word_packed = pack_if_HEX_notation ($word);

  # recover the plaintext header so the hash can be regenerated byte for byte

  my $key = kwallet_password2hash ($word_packed);

  my $ct_sw = kwallet_alter_endianity (pack ("H*", $ct));

  my $ecb = Crypt::Mode::ECB->new ('Blowfish', 0);

  my $plain = substr ($ct_sw, 0, 8) . $ecb->decrypt (substr ($ct_sw, 8, 56), $key);

  my $new_hash = module_generate_hash ($word_packed, "", unpack ("H*", $plain), $ct_len);

  return ($new_hash, $word);
}

1;
