#!/usr/bin/env perl

##
## Author......: See docs/credits.txt
## License.....: MIT
##

use strict;
use warnings;

use Crypt::Mode::CBC;
use Crypt::PBKDF2;

sub module_constraints { [[0, 256], [112, 112], [-1, -1], [-1, -1], [-1, -1]] }

# KWallet byte swaps every 32 bit word of the file before it hands it to Blowfish,
# which is a KDE bug the on disk format is stuck with.

sub kwallet_alter_endianity
{
  my $in = shift;

  my $out = "";

  for (my $i = 0; $i < length ($in); $i += 4)
  {
    $out .= scalar reverse substr ($in, $i, 4);
  }

  return $out;
}

# the 64 byte header before encryption: 8 byte random block (also the CBC IV), the
# payload size and 52 byte of payload. The size field is stored reversed here because
# the reader swaps it back after decrypting, and the payload needs at least 12 zero
# bytes for the reader to accept the key - a real wallet has around 30.

sub kwallet_random_plain
{
  my $ct_len = shift;

  my $payload = random_bytes (52);

  for (my $i = 0; $i < 52; $i += 3)
  {
    substr ($payload, $i, 1) = "\x00";
  }

  return unpack ("H*", random_bytes (8) . scalar reverse (pack ("N", $ct_len - 12)) . $payload);
}

sub module_generate_hash
{
  my $word   = shift;
  my $salt   = shift;
  my $iter   = shift // 50000;
  my $ct_len = shift // 88;
  my $plain  = shift;

  $plain = kwallet_random_plain ($ct_len) unless defined $plain;

  $plain = pack ("H*", $plain);

  my $b_salt = pack ("H*", $salt);

  my $pbkdf2 = Crypt::PBKDF2->new
  (
    hasher     => Crypt::PBKDF2->hasher_from_algorithm ('HMACSHA2', 512),
    iterations => $iter,
    output_len => 56
  );

  my $key = $pbkdf2->PBKDF2 ($b_salt, $word);

  my $cbc = Crypt::Mode::CBC->new ('Blowfish', 0);

  # the IV has to live in a plain scalar, CryptX rejects the lvalue substr returns

  my $iv = substr ($plain, 0, 8);

  my $ct_sw = $iv . $cbc->encrypt (substr ($plain, 8, 56), $key, $iv);

  my $ct = kwallet_alter_endianity ($ct_sw);

  my $hash = sprintf ('$kwallet$%d$%s$1$%d$%s$%d', $ct_len, unpack ("H*", $ct), length ($b_salt), $salt, $iter);

  return $hash;
}

sub module_verify_hash
{
  my $line = shift;

  my ($hash, $word) = split (':', $line);

  return unless defined $hash;
  return unless defined $word;

  my @data = split ('\$', $hash);

  return unless scalar @data == 8;

  shift @data; # leading empty field

  my $signature = shift @data;
  my $ct_len    = shift @data;
  my $ct        = shift @data;
  my $minor     = shift @data;
  my $salt_len  = shift @data;
  my $salt      = shift @data;
  my $iter      = shift @data;

  return unless $signature eq 'kwallet';
  return unless $minor     eq '1';
  return unless length ($ct) == 128;
  return unless length ($salt) == $salt_len * 2;

  my $word_packed = pack_if_HEX_notation ($word);

  # recover the plaintext header so the hash can be regenerated byte for byte

  my $b_salt = pack ("H*", $salt);

  my $pbkdf2 = Crypt::PBKDF2->new
  (
    hasher     => Crypt::PBKDF2->hasher_from_algorithm ('HMACSHA2', 512),
    iterations => $iter,
    output_len => 56
  );

  my $key = $pbkdf2->PBKDF2 ($b_salt, $word_packed);

  my $ct_sw = kwallet_alter_endianity (pack ("H*", $ct));

  my $cbc = Crypt::Mode::CBC->new ('Blowfish', 0);

  my $iv = substr ($ct_sw, 0, 8);

  my $plain = $iv . $cbc->decrypt (substr ($ct_sw, 8, 56), $key, $iv);

  my $new_hash = module_generate_hash ($word_packed, $salt, $iter, $ct_len, unpack ("H*", $plain));

  return ($new_hash, $word);
}

1;
